version: '3'
services:
  bot:
    image: ${IMAGE_NAME}:latest
    deploy:
      replicas: 1
    environment:
      - ENV_FILE=/run/secrets/BotLockerEnv
      - DATA_DIR=/data
    volumes:
      - botlocker-data:/data
    secrets:
      - BotLockerEnv

volumes:
  botlocker-data:

secrets:
  BotLockerEnv:
    external: true
